### ISSUE TITLE
Error for View Orientation Distribution

### ISSUE THREAD

**Issue by menmt0930** [evanseitz/ManifoldEM_Python#2]
I prepared Alignment File and Image Stack from a CryoSPASRC Non-uniform refinement job by using csparc2star. I tried "View Orientation Distribution" and encountered this error.
Is there any problem in my .star alignment file?

2024-05-10 01:32:28.295 python[36683:48961184] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
Processing orientations...
RELION Optics Group found.
Processing orientations...
RELION Optics Group found.
Traceback (most recent call last):
  File "/Users/menmt0930/opt/anaconda3/envs/manifold/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 2022, in shape
    result = a.shape
AttributeError: 'list' object has no attribute 'shape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/menmt0930/ManifoldEM_Python/ManifoldEM_GUI.py", line 9232, in onTabChange
    Data.op(P1.user_alignment)
  File "/Users/menmt0930/ManifoldEM_Python/modules/Data.py", line 124, in op
    if p.resProj == 0 and (np.shape(CG)[0] > 2):
  File "/Users/menmt0930/opt/anaconda3/envs/manifold/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 2024, in shape
    result = asarray(a).shape
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2509,) + inhomogeneous part.
Abort trap: 6

**Comment by evanseitz** [comment]
Hi @menmt0930,

Currently, ManifoldEM is only set up to read in RELION alignment files. For analyses using CryoSPARC, you'll need to convert the alignment file into RELION format. Our code for reading the RELION format can be found in [1]. If you would like to review a RELION format file that works with ManifoldEM, please see our tutorial dataset, or the Data Portal entry linked with [2].

[1] https://github.com/evanseitz/ManifoldEM_Python/blob/main/modules/read_alignfile.py
[2] https://ieeexplore.ieee.org/document/9773954

**Comment by menmt0930** [comment]
Seems my .star file is okay. I'd like to do a test run with my ManifoldEM, but in the 'demo' folder here I can only find the averaged map and no particle stack file and alignment file. Where can I get all demo files needed for a test run?

**Comment by evanseitz** [comment]
Instructions for running our demo can be found in the tutorial PDF (Chapter 1 has links to download the demo data)

https://github.com/evanseitz/ManifoldEM_Python/blob/main/ManifoldEM_Manual_Beta.pdf

**Comment by menmt0930** [comment]
Thank you!
I finally found that the issued was from the version of numpy. I reinstalled an older version and now it works with my dataset.

**Comment by evanseitz** [comment]
Great, glad to hear it!
